# -*- coding: utf-8 -*-
"""Project Euler #2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

Project Euler: https://projecteuler.net/problem=2
Hackerrank: https://www.hackerrank.com/contests/projecteuler/challenges/euler002/problem
"""


def sum_even_fibonacci_numbers(number):
    a = 1
    b = 2
    s = 2

    while b < number:
        b = b + a
        a = b - a

        if b % 2 == 0 and b < number:
            s += b

    return s


if __name__ == '__main__':
    t = int(input().strip())

    results = []

    for _ in range(t):
        n = int(input().strip())
        print(sum_even_fibonacci_numbers(n))
